services:
  db:
    image: postgres:16
    container_name: quizz-app-db
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=securepassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./quizz-app-backend
      dockerfile: Dockerfile
    container_name: quizz-app-backend
    ports:
      - "8000:8000"
    volumes:
      - ./quizz-app-backend/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=***
      - OPEN_API_MODEL=gpt-4o-mini

      # Settings
      - DJANGO_SECRET_KEY=G8oCsQIVa9mW-qH6sR57U3zJgc1WysgAcCEOx-fwJ7eK3wgG3xxb1orMQDBTgTj3sM2VKHw_
      - DJANGO_DEBUG=1
      - DJANGO_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

      # Database
      - DATABASE_NAME=database
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=securepassword123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=quizz_app
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: quizz-app-frontend
    working_dir: /app
    command: sh -c "npm install --force && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./quizz-app-frontend:/app
    environment:
      - NODE_ENV=development
      - DJANGO_URL=http://backend:8000

volumes:
  postgres_data: