# Generated by Django 5.1.3 on 2024-11-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Options",
            new_name="Option",
        ),
        migrations.AddField(
            model_name="quiz",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userstats",
            name="rating",
            field=models.FloatField(default=2.5),
        ),
    ]
