# Generated by Django 5.1.3 on 2024-11-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_rename_options_option_quiz_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("programming", "Języki Programowania"),
                    ("math", "Matematyka"),
                    ("history", "Historia"),
                    ("science", "Nauki Przyrodnicze"),
                    ("geography", "Geografia"),
                    ("art", "Sztuka"),
                    ("language", "Kultura i Język"),
                    ("business", "Biznes i Ekonomia"),
                    ("technology", "Technologia"),
                    ("other", "Inna"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
