# Generated by Django 5.1.3 on 2024-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_quiz_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
